Models/Patient.cs
namespace WebApplication1.Models
{
 


        public class Patient
        {
            public int PatientID { get; set; }
            public string PatientName { get; set; }
            public string PatientLastName { get; set; }
            public DateTime PatientDateOfBirth { get; set; } // Nullable DateTime
            public string PatientGender { get; set; }
            public string? PatientAddress { get; set; }
            public string? PostalCode { get; set; }
            public string PatientContactNumber { get; set; }
            public string? PatientEmailAddress { get; set; }
            public string? PatientEmployerCellNo { get; set; }
            public string? PatientOccupation { get; set; }
            public string? CreatedBy { get; set; }
            public string? UpdatedBy { get; set; }
            public DateTime CreatedDate { get; set; } = DateTime.Now;
        public string? SpouseName { get; set; }
            public string? SpouseContactNo { get; set; }
            public DateTime UpdatedDate { get; set; } = DateTime.Now;
        public bool isActive { get; set; }
            public bool isPatientStudent { get; set; }
            public string? School { get; set; }
            public string? Grade { get; set; }
            public string? Teacher { get; set; }
            public string? SchoolContactNo { get; set; }
            public string? FatherDetails { get; set; }
            public string? FathersName { get; set; }
            public string? FatherOccupation { get; set; }
            public string? FatherAddress { get; set; }
            public string? FatherWorkPhone { get; set; }
            public string? FatherCellPhone { get; set; }
            public string? FatherEmail { get; set; }
            public string? MotherDetails { get; set; }
            public string? MotherName { get; set; }
            public string? MotherOccupation { get; set; }
            public string? MotherAddress { get; set; }
            public string? MotherCellphone { get; set; }
            public string? MotherWorkPhone { get; set; }
            public string? MotherEmail { get; set; }


        public string? IDNumber { get; set; }
        public List<Doctor>? Doctor { get; set; }

        public List<ClinicalRecord>? ClinicalRecords { get; set; }

    }

     


}
 

Controllers/PatientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "ViewPatient")]


    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public PatientsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patient.ToListAsync());
        }
        [HttpPost]
        public IActionResult Search(string searchCriteria, string searchTerm)
        {
            IQueryable<Patient> patients = _context.Patient;

            if (string.IsNullOrEmpty(searchTerm))
            {
                return View("Index", patients.ToList());
            }

            switch (searchCriteria)
            {
                case "patientName":
                    patients = patients.Where(p => p.PatientName.Contains(searchTerm));
                    break;
                case "patientLastName":
                    patients = patients.Where(p => p.PatientLastName.Contains(searchTerm));
                    break;
                case "disorder":
                    patients = patients.Where(p => p.PatientEmailAddress.Contains(searchTerm));
                    break;
                case "clinic":
                    patients = patients.Where(p => p.PatientContactNumber.Contains(searchTerm));
                    break;
                case "idNumber":
                    patients = patients.Where(p => p.IDNumber.Contains(searchTerm));
                    break;
            }

            return View("Index", patients.ToList());
        }
        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient
                .FirstOrDefaultAsync(m => m.PatientID == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }
        [HttpGet]
        [Authorize(Roles = "CreatePatient")]
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["LoggedInUser"] = user.UserName;
            return View("Create");
        }
        [HttpPost]

 
        public async Task<IActionResult> Create(Patient patient)
        {
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                patient.CreatedBy = user.UserName;
                patient.UpdatedBy = user.UserName;
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoggedInUser"] = user.UserName;
            return View(patient);
        }

        // GET: Patients/Edit/5
        [Authorize(Roles = "CreatePatient")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientID,PatientName,PatientLastName,PatientDateOfBirth,IDNumber,PatientGender,PatientAddress,PostalCode,PatientContactNumber,PatientEmailAddress,PatientEmployerCellNo,PatientOccupation,CreatedBy,UpdatedBy,CreatedDate,SpouseName,SpouseContactNo,UpdatedDate,isActive,isPatientStudent,School,Grade,Teacher,SchoolContactNo,FatherDetails,FathersName,FatherOccupation,FatherAddress,FatherWorkPhone,FatherCellPhone,FatherEmail,MotherDetails,MotherName,MotherOccupation,MotherAddress,MotherCellphone,MotherWorkPhone,MotherEmail,OtherDoctorDetails,FamilyDoctorName,FamilyDoctorInstitution,FamilyDoctorContactNo,PsychologistName,PsychologistInstitution,PsychologistContactNo,SocialWorkerName,SocialWorkerInstitution,SocialWorkerContactNo,OccupationalTherapist,OccupationalTherapistName,OccupationalTherapistInstitution,OccupationalTherapistContactNo")] Patient patient)
        {
            if (id != patient.PatientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.PatientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        [Authorize(Roles = "DeletePatient")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient
                .FirstOrDefaultAsync(m => m.PatientID == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patient.FindAsync(id);
            if (patient != null)
            {
                _context.Patient.Remove(patient);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patient.Any(e => e.PatientID == id);
        }
 
    }
}

Views/Patients/Delete.cshtml
@model WebApplication1.Models.Patient

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientDateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientDateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientContactNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientEmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientEmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientEmployerCellNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientEmployerCellNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientOccupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientOccupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpouseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpouseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpouseContactNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpouseContactNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isPatientStudent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isPatientStudent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.School)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.School)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchoolContactNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchoolContactNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FathersName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FathersName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherOccupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherOccupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherWorkPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherWorkPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherCellPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherCellPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FatherEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FatherEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherOccupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherOccupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherCellphone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherCellphone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherWorkPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherWorkPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotherEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotherEmail)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PatientID" />
        <input type="submit" value="Delete" id="btn-delete-patient" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
<script>
    $(document).ready(function () {
        $("#btn-delete-patient").on("click", function () {
            var formData = new FormData();
            formData.append("id", $("#PatientID").val());
            $.ajax({
                type: 'DELETE',
                url: '@Url.Action("delete", "File")',
                contentType: false,
                processData: false,
                cache: false,
                data: formData,
                success: successCallback,
                error: errorCallback
            });
        });

        function errorCallback() {
            bootbox.alert("Something went wrong please contact admin.");
        }
        function successCallback(response) {
            if (response.responseCode == 0) {
                resetForm();
                bootbox.alert(response.responseMessage, function () {

                    //PERFORM REMAINING LOGIC that you need when patient is deleted
                });
            }
            else {
                bootbox.alert(response.ResponseMessage);
            }
        };
    });

</script>

Views/Patients/Details.cshtml
@model WebApplication1.Models.Patient

@{
    ViewData["Title"] = "Details";
}

<h1>Patient Details</h1>

<div>
 
    <hr />
    <dl class="row">
        <dt class = "col-md-6">
       First Name 
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientName)
        </dd>
        <dt class = "col-md-6">
         Surname
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientLastName)
        </dd>
        <dt class = "col-md-6">
         Date of Birth
        </dt>

        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientDateOfBirth)
        </dd>
        <dt class="col-md-6">
           Identity Number
        </dt>
        <dd class="col-md-6">
            @Html.DisplayFor(model => model.IDNumber)
        </dd>

        <dt class = "col-md-6">
           Gender
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientGender)
        </dd>
        <dt class = "col-md-6">
           Address
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientAddress)
        </dd>
        <dt class = "col-md-6">
           Postal Code
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-md-6">
          Contact Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientContactNumber)
        </dd>
        <dt class = "col-md-6">
          Email Address
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientEmailAddress)
        </dd>
        <dt class = "col-md-6">
          Employer Cell Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientEmployerCellNo)
        </dd>
        <dt class = "col-md-6">
          Patient Occupation 
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.PatientOccupation)
        </dd>

        <dt class = "col-md-6">
        Spouse Name
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.SpouseName)
        </dd>
        <dt class = "col-md-6">
           Spouse Contact Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.SpouseContactNo)
        </dd>

 
 
        <dt class = "col-md-6">
          School Name
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.School)
        </dd>
        <dt class = "col-md-6">
          Grade
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-md-6">
          Teacher Name
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.Teacher)
        </dd>
        <dt class = "col-md-6">
         School Contact Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.SchoolContactNo)
        </dd>
        <dt class = "col-md-6">
            Fathers Details 
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherDetails)
        </dd>
        <dt class = "col-md-6">
            Father's Name 
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FathersName)
        </dd>
        <dt class = "col-md-6">
           Father's Occupation
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherOccupation)
        </dd>
        <dt class = "col-md-6">
            Father's Address
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherAddress)
        </dd>
        <dt class = "col-md-6">
           Father's Work Contact Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherWorkPhone)
        </dd>
        <dt class = "col-md-6">
           Father's Cell Number
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherCellPhone)
        </dd>
        <dt class = "col-md-6">
            Father's Email Address
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.FatherEmail)
        </dd>
        <dt class = "col-md-6">
           Mother's Details
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherDetails)
        </dd>
        <dt class = "col-md-6">
          Mother's Name
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherName)
        </dd>
        <dt class = "col-md-6">
           Mother's Occupation
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherOccupation)
        </dd>
        <dt class = "col-md-6">
            Mother's' Address
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherAddress)
        </dd>
        <dt class = "col-md-6">
            Mother's CellNumber
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherCellphone)
        </dd>
        <dt class = "col-md-6">
            Mother's Work Phone
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherWorkPhone)
        </dd>
        <dt class = "col-md-6">
            Mother's Email
        </dt>
        <dd class = "col-md-6">
            @Html.DisplayFor(model => model.MotherEmail)
        </dd>
        <dt class="col-md-6">
            Created by
        </dt>
        <dd class="col-md-6">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-md-6">
            Last Updated By
        </dt>
        <dd class="col-md-6">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt class="col-md-6">
            Created Date
        </dt>
        <dd class="col-md-6">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-md-6">
            Last Updated Date
        </dt>
        <dd class="col-md-6">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PatientID" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to Patient List</a>
</div>

Views/Patients/Index.cshtml
@model IEnumerable<WebApplication1.Models.Patient>

@{
    ViewData["Title"] = "Index";
}

<h1>
    Patients
    
</h1>
<p>
    <button onclick="location.href='@Url.Action("Create", "Patients")'" class="btn btn-primary mb-2">Create New</button>
</p>
<div class="container">
    <form method="post" action="/Patients/Search">
        <div class="form-row row">
            <div class="col-md-3">
                <select class="form-control mb-2" id="searchCriteria" name="searchCriteria">
                    <option value="patientName">Patient Name</option>
                    <option value="patientLastName">Patient Last Name</option>
                    <option value="email">Email</option>
                    <option value="contactNumber">Patient Contact Number</option>
                    <option value="idNumber">ID Number</option>
                </select>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control mb-2" id="searchTerm" name="searchTerm" placeholder="Enter search term" minlength="3" />
                <small class="form-text text-muted"><strong>Minimum 3 characters required.</strong></small>
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-primary mb-2">Search</button>
            </div>  
            
        </div>
        
    </form>
    
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<div class="container">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th> </th>
                    <th>Patient Name</th>
                    <th>Last Name</th>
                    <th>Date of Birth</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Postal Code</th>
                    <th>Contact Number</th>
                    <th>Email Address</th>
                    <th>Employer Cell No</th>
                    <th>Occupation</th>
                    <th>Created By</th>
                    <th>Updated By</th>
                    <th>Created Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.PatientID" class="btn btn-primary">Edit</a>
                            <a asp-action="Details" asp-route-id="@item.PatientID" class="btn btn-primary">View</a>
                            @* <a asp-action="Delete" asp-route-id="@item.PatientID">Delete</a> *@
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.PatientName)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientLastName)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientDateOfBirth)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientGender)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientAddress)</td>
                        <td>@Html.DisplayFor(modelItem => item.PostalCode)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientContactNumber)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientEmailAddress)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientEmployerCellNo)</td>
                        <td>@Html.DisplayFor(modelItem => item.PatientOccupation)</td>
                        <td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
                        <td>@Html.DisplayFor(modelItem => item.UpdatedBy)</td>
                        <td>@Html.DisplayFor(modelItem => item.CreatedDate)</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Patients/PatientSearch.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    <!DOCTYPE html>
    <html>
    <head>
        <title>Patient Search</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <h2>Search Patients</h2>
            <form method="post" action="/Patient/Search">
                <div class="form-group">
                    <label for="searchCriteria">Search By:</label>
                    <select class="form-control" id="searchCriteria" name="searchCriteria">
                        <option value="patientName">Patient Name</option>
                        <option value="patientLastName">Patient Last Name</option>
                        <option value="disorder">Disorder</option>
                        <option value="clinic">Clinic</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="searchTerm">Search Term:</label>
                    <input type="text" class="form-control" id="searchTerm" name="searchTerm" required />
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>
    </html>


}